### ISSUE TITLE
Problem building with open dylan 2019.1

### ISSUE THREAD

**Issue by cpaulbond** [cgay/shootout#1]
I have recently installed open dylan on my mac (Mojave) and am trying to build the shootout code.  When I build I see the error below.  I have found that if I create a separate library file, and move the define library and module blocks to the new file everything compiles as expected.  Is there a problem with how I am building? 
```
$ dylan-compiler -build ackermann.lid
Opened project ackermann (/Users/pbond/wrk/public/dylan/shootout/ackermann.hdp)
Processing library ackermann
Loading namespace for library ackermann

Internal error: No applicable method, applying {<sealed-generic-function>: top-level-convert-using-definition} to {<simple-object-vector>: #f, #f, {<function-macro-fragment>}}.
Exiting with return code -1
```

**Comment by cgay** [comment]
No, you're not doing anything wrong.  The support for "single file libraries" has bit rotted over time, I'm afraid.  Putting the library and module definitions in a separate file is the right fix. Want to send some pull requests?!  :-)

Even though it was forked from here, https://github.com/dylan-lang/shootout should probably be considered the canonical home of this repo.

**Comment by cpaulbond** [comment]
Pull requests sounds like a reasonable idea.  I will submit them to https://github.com/dylan-lang/shootout.
